apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-sm
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            namespace: external-secrets
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-creds
            namespace: external-secrets
            key: secret-access-key