apiVersion: v1
kind: Secret
metadata:
  name: simpledevice-api-secrets
type: Opaque
stringData:
  ConnectionStrings__Default: "Host=postgres-postgresql;Port=5432;Database=devices;Username=app;Password=app"
