apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-simpledevice-dev-postgres
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/simpledevice-dev/postgres
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: simpledevice-dev
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-simpledevice-dev-postgres
  storageClassName: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: simpledevice-dev
type: Opaque
stringData:
  POSTGRES_DB: devices_dev
  POSTGRES_USER: app
  POSTGRES_PASSWORD: app
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: simpledevice-dev
spec:
  selector:
    app: postgres
  ports:
  - name: pg
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: simpledevice-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
      - name: init-permissions
        image: busybox:1.36
        command: ["sh","-c","chown -R 999:999 /var/lib/postgresql/data || true"]
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-data
